algo = input('Digite qualquer coisa: ')
print(algo, type(algo))
print('É um valor numérico? {}!'.format(algo.isnumeric()))
print('É um valor alfabético? {}!'.format(algo.isalpha()))
print('É um valor alfabético e/ou numérico? {}!'.format(algo.isalnum()))
print('É um valor decimal? {}!'.format(algo.isdecimal()))
print('É um título? {}!'.format(algo.istitle()))
print('É um dígito? {}!'.format(algo.isdigit()))
print('O valor possui algo alfabético completamente maiúsculo? {}!'.format(algo.isupper()))
print('O valor possui algo alfabético completamente minúsculo? {}!'.format(algo.islower()))
print('É um identificador válido? {}'.format(algo.isidentifier()))
print('É um valor que pode ser impresso? {}!'.format(algo.isprintable()))
print('É somente formado por espaços? {}!'.format(algo.isspace()))
print('É vazio e/ou possui algo ASCII? {}!'.format(algo.isascii()))
